# Generated by Django 4.1.7 on 2023-06-03 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(default='Z', max_length=7, unique=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.state')),
            ],
        ),
    ]
