# Generated by Django 4.1.7 on 2023-06-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_lga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lga',
            name='code',
        ),
    ]
