# Generated by Django 4.1.7 on 2023-06-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='object_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
