# Generated by Django 4.1.4 on 2023-01-03 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_subject_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectgroup',
            name='code',
        ),
    ]
