# Generated by Django 4.1.4 on 2023-01-04 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_remove_subjectgroup_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('_class', 'class_arm')},
        ),
    ]
