# Generated by Django 4.1.4 on 2023-01-04 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_testtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='type',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='school.testtype'),
            preserve_default=False,
        ),
    ]
