# Generated by Django 4.1.4 on 2023-01-04 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_student_sex_teacher_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.testtype'),
        ),
    ]
