# Generated by Django 4.1.4 on 2023-01-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='title',
            field=models.CharField(choices=[('F', 'First Term'), ('S', 'Second Term'), ('T', 'Third term')], default='F', max_length=1),
            preserve_default=False,
        ),
    ]
