# Generated by Django 4.1.4 on 2023-01-05 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_alter_term_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='score',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='school.session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='school.term'),
            preserve_default=False,
        ),
    ]
