# Generated by Django 4.1.4 on 2023-01-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_score_date_created_score_session_score_term'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('student', 'teacher', 'term', 'type')},
        ),
    ]
