# Generated by Django 4.1.4 on 2023-01-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_alter_score_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='last_edited',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
