# Generated by Django 4.1.4 on 2023-01-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('days', models.ManyToManyField(to='school.day')),
            ],
        ),
    ]
