# Generated by Django 4.1.4 on 2023-01-05 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_attendancemark_day_attendancemark_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancemark',
            old_name='teacher',
            new_name='class_teacher',
        ),
    ]
