# Generated by Django 4.1.4 on 2023-01-05 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_rename_teacher_attendancemark_class_teacher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancemark',
            unique_together={('student', 'day', 'week')},
        ),
    ]
