# Generated by Django 4.1.4 on 2023-01-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_week_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='title',
            field=models.CharField(choices=[('First', 'First Week'), ('Second', 'Second Week'), ('Third', 'Third Week'), ('Fourth', 'Fourth Week'), ('Fifth', 'Fifth Week')], max_length=255),
        ),
    ]
