# Generated by Django 4.1.4 on 2023-01-12 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
    ]
