# Generated by Django 4.1.4 on 2023-01-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0033_remove_student_first_name_remove_student_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(default='A', max_length=255),
            preserve_default=False,
        ),
    ]
