# Generated by Django 4.1.4 on 2023-01-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0035_remove_teacher_first_name_remove_teacher_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_year',
            field=models.PositiveBigIntegerField(default=2017),
            preserve_default=False,
        ),
    ]
