# Generated by Django 4.1.5 on 2023-01-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0036_student_admission_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='school/images'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(null=True, upload_to='school/images'),
        ),
    ]
