# Generated by Django 4.1.5 on 2023-02-12 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0039_remove_student_middle_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('student', 'teacher', 'term', 'session', 'type')},
        ),
    ]
