# Generated by Django 4.1.5 on 2023-02-16 20:27

from django.db import migrations, models
import school.validators


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0040_alter_score_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='_class',
            new_name='managed_class',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='class_arm',
            new_name='managed_class_arm',
        ),
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.PositiveSmallIntegerField(validators=[school.validators.validate_score_size]),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('managed_class', 'managed_class_arm')},
        ),
    ]
