# Generated by Django 4.1.7 on 2023-06-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0041_rename__class_teacher_managed_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
