# Generated by Django 4.1.7 on 2023-06-10 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0045_scoresheet_score_scoresheet'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('student', 'scoresheet', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='scoresheet',
            unique_together={('teacher', 'term', 'session')},
        ),
    ]
