# Generated by Django 4.1.7 on 2023-06-23 05:21

from django.db import migrations
from school.models import ClassArm, Class


def seed_data(apps, schema_editor):
    class_data = [
        Class(title='JSS 1'),
        Class(title='JSS 2'),
        Class(title='JSS 3'),
        Class(title='SSS 1'),
        Class(title='SSS 2'),
        Class(title='SSS 3'),
    ]

    arms_data = [
        ClassArm(title='A'),
        ClassArm(title='B'),
        ClassArm(title='C'),
        ClassArm(title='D'),
    ]

    Class.objects.bulk_create(class_data)
    ClassArm.objects.bulk_create(arms_data)


def revert_data(apps, schema_editor):
    ClassArm.objects.all().delete()
    Class.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0046_alter_score_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_data, revert_data)
    ]
