# Generated by Django 4.1.7 on 2023-07-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0047_seed_classes_arms_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='group',
        ),
        migrations.AddField(
            model_name='subject',
            name='groups',
            field=models.ManyToManyField(related_name='subjects', to='school.subjectgroup'),
        ),
    ]
