# Generated by Django 4.1.7 on 2023-07-06 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0049_seed_subject_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='scoresheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.scoresheet'),
        ),
    ]
