# Generated by Django 4.1.7 on 2023-07-06 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0050_alter_score_scoresheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresheet',
            name='_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='school.class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='class_arm',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='school.classarm'),
            preserve_default=False,
        ),
    ]
