# Generated by Django 4.1.7 on 2023-07-07 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0051_scoresheet__class_scoresheet_class_arm'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='school.session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='school.term'),
            preserve_default=False,
        ),
    ]
