# Generated by Django 4.1.7 on 2023-08-10 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0052_score_session_score_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='_class',
            field=models.ForeignKey(
                db_column='class_id', on_delete=django.db.models.deletion.PROTECT, to='school.class'),
        ),
    ]
