# Generated by Django 4.2.7 on 2023-12-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0053_alter_student__class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='session',
        ),
        migrations.RemoveField(
            model_name='score',
            name='term',
        ),
    ]
