# Generated by Django 4.2.7 on 2023-12-04 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0054_remove_score_session_remove_score_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='managed_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_set', to='school.class'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='managed_class_arm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_set', to='school.classarm'),
        ),
    ]
